

services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/Desktop/Django/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog -d blog"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: