# Generated by Django 6.0.4 on 2026-04-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%y/%m/%d/"
            ),
        ),
    ]
