# Generated by Django 6.0.4 on 2026-07-29 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_profile_img"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_created_idx",
            old_name="blog_commen_created_0e6ed4_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="post_publish_idx",
            old_name="blog_post_publish_bb7600_idx",
        ),
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "active", "created"], name="comment_post_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-publish"], name="post_status_publish_idx"
            ),
        ),
    ]
