# Generated by Django 6.0.7 on 2026-08-02 23:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "blog",
            "0010_rename_blog_commen_created_0e6ed4_idx_comment_created_idx_and_more",
        ),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "title", config="simple", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "body", config="simple", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("simple"),
                ),
                name="post_search_gin_idx",
            ),
        ),
    ]
