# Generated by Django 6.0.7 on 2026-08-02 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_post_post_search_gin_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish"],
                "permissions": [("publish_post", "Can publish and schedule posts")],
            },
        ),
    ]
