# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models
from django.utils.text import slugify


def make_slugs_globally_unique(apps, schema_editor):
    post_model = apps.get_model("blog", "Post")
    used_slugs = set()
    for post in post_model.objects.order_by("pk").iterator():
        base_slug = post.slug or slugify(post.title, allow_unicode=True) or "post"
        base_slug = base_slug[:250]
        candidate = base_slug
        suffix = 2
        while candidate in used_slugs:
            suffix_text = f"-{suffix}"
            candidate = f"{base_slug[: 250 - len(suffix_text)]}{suffix_text}"
            suffix += 1
        used_slugs.add(candidate)
        if candidate != post.slug:
            post_model.objects.filter(pk=post.pk).update(slug=candidate)


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_options"),
    ]

    operations = [
        migrations.RunPython(
            make_slugs_globally_unique,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="post_status_publish_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-publish", "-id"],
                name="post_status_publish_idx",
            ),
        ),
    ]
