# Generated by Django 6.0.7 on 2026-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="presentations/images/%Y/%m/%d/"
            ),
        ),
    ]
