# Generated by Django 6.0.7 on 2026-08-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0002_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
